Repository woowacourse-teams/2023-co-kirikiri, pull requests merged in 2023-08, with the labels that each got.

#46 [feat/CK-95] 골룸 상단부분 데이터를 매핑한다
  client/src/apis/axios/client.ts
  client/src/apis/goalRoom.ts
  client/src/components/goalRoomDahsboardPage/goalRoomDashboardContent/GoalRoomDashboardContent.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomDashboardHeader/GoalRoomDashboardHeader.tsx
  client/src/constants/goalRoom/.gitkeep
  client/src/constants/goalRoom/recruitmentStatus.ts
  client/src/hooks/_common/useValidParams.ts
  client/src/hooks/queries/goalRoom.ts
  client/src/index.tsx
  client/src/mocks/fixtures/goalRoom.ts
  client/src/mocks/handlers/goalRoomHander.ts
  client/src/mocks/handlers/index.ts
  client/src/myTypes/goalRoom/.gitkeep
  client/src/myTypes/goalRoom/internal.ts
  client/src/myTypes/goalRoom/remote.ts
Labels: feature 🔅, FE 👨‍👨‍👧

#51 [feat/CK-123] 로그인 서버 연결 및 웹팩 설정을 변경한다
  client/src/apis/axios/client.ts
  client/src/apis/user.ts
  client/src/components/signUpPage/SignUpForm.tsx
  client/src/myTypes/user/remote.ts
  client/webpack.prod.js
Labels: feature 🔅, FE 👨‍👨‍👧

#52 [feat/CK-97] 투두리스트 조회 데이터 매핑 및 스타일링
  client/src/components/goalRoomDahsboardPage/goalRoomDahsboardTodo/GoalRoomDashboardTodo.styles.ts
  client/src/components/goalRoomDahsboardPage/goalRoomDahsboardTodo/GoalRoomDashboardTodo.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomDahsboardTodo/singleTodo/SingleTodo.styles.ts
  client/src/components/goalRoomDahsboardPage/goalRoomDahsboardTodo/singleTodo/SingleTodo.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomDashboardContent/GoalRoomDashboardContent.styles.ts
  client/src/components/goalRoomDahsboardPage/goalRoomDashboardContent/GoalRoomDashboardContent.tsx
  client/src/components/icons/svgIcons.tsx
  client/src/hooks/_common/useHover.ts
  client/src/mocks/fixtures/goalRoom.ts
  client/src/styles/animations.ts
Labels: feature 🔅, FE 👨‍👨‍👧

#53 [feat/CK-96] 투두리스트 인증 피드 데이터 매핑 및 스타일링을 구현한다
  client/src/components/goalRoomDahsboardPage/goalRoomCertificationFeed/GoalRoomCertificationFeed.styles.ts
  client/src/components/goalRoomDahsboardPage/goalRoomCertificationFeed/GoalRoomCertificationFeed.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomDashboardContent/GoalRoomDashboardContent.tsx
  client/src/mocks/fixtures/goalRoom.ts
  client/src/styles/theme.ts
  client/webpack.common.js
Labels: feature 🔅, FE 👨‍👨‍👧

#55 [feat/CK-82] 골룸 생성을 구현한다
  client/src/App.tsx
  client/src/apis/goalRoom.ts
  client/src/apis/roadmap.ts
  client/src/components/goalRoomCreatePage/.gitkeep
  client/src/components/goalRoomCreatePage/createGoalRoom/CreateGoalRoom.styles.ts
  client/src/components/goalRoomCreatePage/createGoalRoom/CreateGoalRoom.tsx
  client/src/components/goalRoomCreatePage/createGoalRoomForm/CreateGoalRoomForm.styles.ts
  client/src/components/goalRoomCreatePage/createGoalRoomForm/CreateGoalRoomForm.tsx
  client/src/components/goalRoomCreatePage/inputField/InputField.styles.ts
  client/src/components/goalRoomCreatePage/inputField/InputField.tsx
  client/src/components/goalRoomCreatePage/pageSection/PageSection.styles.ts
  client/src/components/goalRoomCreatePage/pageSection/PageSection.tsx
  client/src/hooks/_common/useFormInput.ts
  client/src/hooks/queries/goalRoom.ts
  client/src/hooks/queries/roadmap.ts
  client/src/mocks/fixtures/goalRoom.ts
  client/src/myTypes/goalRoom/internal.ts
  client/src/myTypes/goalRoom/remote.ts
  client/src/myTypes/roadmap/internal.ts
  client/src/myTypes/roadmap/remote.ts
  client/src/pages/goalRoomCreatePage/.gitkeep
  client/src/pages/goalRoomCreatePage/GoalRoomCreatePage.styles.ts
  client/src/pages/goalRoomCreatePage/GoalRoomCreatePage.tsx
  client/src/tests/utilTests/convertFieldsToNumber.test.ts
  client/src/utils/_common/convertFieldsToNumber.ts
Labels: feature 🔅, FE 👨‍👨‍👧

#45 [feat/CK-86] 로드맵의 태그를 생성한다
  client/src/components/roadmapCreatePage/roadmapCreateForm/RoadmapCreateForm.tsx
  client/src/components/roadmapCreatePage/tag/Tag.tsx
  client/src/components/roadmapCreatePage/tag/TagItem.tsx
  client/src/components/roadmapCreatePage/tag/tag.styles.ts
  client/src/constants/roadmap/regex.ts
  client/src/constants/roadmap/tag.ts
  client/src/hooks/_common/useValidateInput.ts
  client/src/hooks/roadmap/.gitkeep
  client/src/hooks/roadmap/useCreateTag.ts
Labels: feature 🔅, FE 👨‍👨‍👧

#56 [feat/CK-101] 모달을 약식 추상화한다
  client/src/components/_common/dialog/dialog.tsx
  client/src/components/mainPage/MainPage.tsx
  client/src/context/dialogContext.ts
  client/src/myTypes/_common/dialog.ts
Labels: feature 🔅, FE 👨‍👨‍👧

#57 [Feat/CK-126] develop-client 빌드 오류를 해결한다
  client/src/components/goalRoomCreatePage/createGoalRoomForm/CreateGoalRoomForm.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomDahsboardTodo/singleTodo/SingleTodo.styles.ts
  client/src/mocks/fixtures/goalRoom.ts
  client/src/myTypes/goalRoom/internal.ts
  client/src/myTypes/goalRoom/remote.ts
Labels: fix ⚒️, FE 👨‍👨‍👧

#40 [feat/CK-67] 로드맵 검색 기능을 추가한다
  backend/kirikiri/src/docs/asciidoc/roadmap.adoc
  backend/kirikiri/src/main/java/co/kirikiri/controller/RoadmapController.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/BaseCreatedTimeEntity.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoom.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomRoadmapNodes.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/Roadmap.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapContent.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapNode.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/dto/RoadmapFilterType.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/dto/RoadmapLastValueDto.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/dto/RoadmapSearchDto.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/dto/RoadmapSearchTagName.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/dto/RoadmapSearchTitle.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/roadmap/RoadmapQueryRepository.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/roadmap/RoadmapQueryRepositoryImpl.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/roadmap/dto/RoadmapFilterType.java
  backend/kirikiri/src/main/java/co/kirikiri/service/RoadmapReadService.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/CustomScrollRequest.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/roadmap/request/RoadmapFilterTypeRequest.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/roadmap/request/RoadmapSearchRequest.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/roadmap/response/RoadmapForListResponse.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/roadmap/response/RoadmapResponse.java
  backend/kirikiri/src/main/java/co/kirikiri/service/mapper/RoadmapMapper.java
  backend/kirikiri/src/test/java/co/kirikiri/controller/RoadmapCreateApiTest.java
  backend/kirikiri/src/test/java/co/kirikiri/controller/RoadmapReadApiTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapCreateIntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapReadIntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/dto/RoadmapSearchTagNameTest.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/dto/RoadmapSearchTitleTest.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/roadmap/RoadmapRepositoryTest.java
  backend/kirikiri/src/test/java/co/kirikiri/service/RoadmapReadServiceTest.java
  backend/kirikiri/src/test/resources/org/springframework/restdocs/templates/query-parameters.snippet
Labels: feature 🔅, BE 👨‍👩‍👧‍👦

#47 [feat/CK-68] 사용자가 생성한 로드맵의 목록을 조회하는 기능을 구현한다
  backend/kirikiri/src/docs/asciidoc/goalroom.adoc
  backend/kirikiri/src/docs/asciidoc/roadmap.adoc
  backend/kirikiri/src/main/java/co/kirikiri/controller/GoalRoomController.java
  backend/kirikiri/src/main/java/co/kirikiri/controller/RoadmapController.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomRoadmapNodes.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/dto/GoalRoomLastValueDto.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/dto/RoadmapSearchTitle.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomQueryRepository.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomQueryRepositoryImpl.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/dto/RoadmapGoalRoomsFilterType.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/roadmap/RoadmapQueryRepository.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/roadmap/RoadmapQueryRepositoryImpl.java
  backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomReadService.java
  backend/kirikiri/src/main/java/co/kirikiri/service/RoadmapReadService.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/CustomScrollRequest.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/roadmap/RoadmapGoalRoomsFilterTypeDto.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/roadmap/response/MemberRoadmapResponse.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/roadmap/response/RoadmapGoalRoomResponse.java
  backend/kirikiri/src/main/java/co/kirikiri/service/mapper/GoalRoomMapper.java
  backend/kirikiri/src/main/java/co/kirikiri/service/mapper/RoadmapMapper.java
  backend/kirikiri/src/test/java/co/kirikiri/controller/GoalRoomReadApiTest.java
  backend/kirikiri/src/test/java/co/kirikiri/controller/RoadmapReadApiTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomReadIntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapReadIntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/goalroom/GoalRoomRepositoryTest.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/roadmap/RoadmapRepositoryTest.java
  backend/kirikiri/src/test/java/co/kirikiri/service/GoalRoomReadServiceTest.java
  backend/kirikiri/src/test/java/co/kirikiri/service/RoadmapReadServiceTest.java
Labels: feature 🔅, BE 👨‍👩‍👧‍👦

#49 [feat/CK-69] 사용자 정보 조회 기능을 구현한다
  backend/kirikiri/src/docs/asciidoc/member.adoc
  backend/kirikiri/src/main/java/co/kirikiri/controller/MemberController.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/member/Member.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/member/MemberProfile.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/member/MemberQueryRepository.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/member/MemberQueryRepositoryImpl.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/member/MemberRepository.java
  backend/kirikiri/src/main/java/co/kirikiri/service/MemberService.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/member/response/MemberInformationForPublicResponse.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/member/response/MemberInformationResponse.java
  backend/kirikiri/src/main/java/co/kirikiri/service/mapper/MemberMapper.java
  backend/kirikiri/src/test/java/co/kirikiri/controller/MemberReadApiTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/MemberIntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/member/MemberRepositoryTest.java
  backend/kirikiri/src/test/java/co/kirikiri/service/MemberServiceTest.java
Labels: feature 🔅, BE 👨‍👩‍👧‍👦

#41 [feat/CK-75] 인증 피드 추가 API를 구현한다
  backend/kirikiri/src/docs/asciidoc/goalroom.adoc
  backend/kirikiri/src/docs/asciidoc/roadmap.adoc
  backend/kirikiri/src/main/java/co/kirikiri/controller/GoalRoomController.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/ImageContentType.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/ImageDirType.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/CheckFeed.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoom.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomMember.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomMembers.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomRoadmapNode.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomRoadmapNodes.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/vo/Period.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/member/Member.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/Roadmap.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/CheckFeedRepository.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomQueryRepository.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomQueryRepositoryImpl.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomRepository.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/dto/GoalRoomFilterType.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/member/MemberQueryRepository.java
  backend/kirikiri/src/main/java/co/kirikiri/service/FilePathGenerator.java
  backend/kirikiri/src/main/java/co/kirikiri/service/FilePathRandomGenerator.java
  backend/kirikiri/src/main/java/co/kirikiri/service/FileService.java
  backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomCreateService.java
  backend/kirikiri/src/main/java/co/kirikiri/service/RoadmapCreateService.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/goalroom/GoalRoomFilterTypeDto.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/goalroom/request/CheckFeedRequest.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/goalroom/response/GoalRoomForListResponse.java
  backend/kirikiri/src/main/java/co/kirikiri/service/mapper/GoalRoomMapper.java
  backend/kirikiri/src/main/java/co/kirikiri/service/mapper/RoadmapMapper.java
  backend/kirikiri/src/test/java/co/kirikiri/controller/GoalRoomCreateApiTest.java
  backend/kirikiri/src/test/java/co/kirikiri/controller/MemberReadApiTest.java
  backend/kirikiri/src/test/java/co/kirikiri/controller/RoadmapCreateApiTest.java
  backend/kirikiri/src/test/java/co/kirikiri/domain/goalroom/GoalRoomRoadmapNodeTest.java
  backend/kirikiri/src/test/java/co/kirikiri/domain/goalroom/GoalRoomRoadmapNodesTest.java
  backend/kirikiri/src/test/java/co/kirikiri/domain/goalroom/GoalRoomTest.java
  backend/kirikiri/src/test/java/co/kirikiri/domain/roadmap/RoadmapContentTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomCreateIntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomReadIntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapCreateIntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapReadIntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/auth/RefreshTokenRepositoryTest.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/goalroom/CheckFeedRepositoryTest.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/goalroom/GoalRoomMemberRepositoryTest.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/roadmap/RoadmapContentRepositoryTest.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/roadmap/RoadmapRepositoryTest.java
  backend/kirikiri/src/test/java/co/kirikiri/service/AuthServiceTest.java
  backend/kirikiri/src/test/java/co/kirikiri/service/FileServiceTest.java
  backend/kirikiri/src/test/java/co/kirikiri/service/GoalRoomCreateServiceTest.java
  backend/kirikiri/src/test/java/co/kirikiri/service/GoalRoomServiceIntegrationTest.java
  backend/kirikiri/src/test/resources/application.yml
  backend/kirikiri/src/test/resources/org/springframework/restdocs/templates/request-parts.snippet
Labels: feature 🔅, BE 👨‍👩‍👧‍👦

#59 [feat/CK-124] 투두리스트, 인증피드 모달을 구현하고 생성 기능을 매핑한다.
  client/.eslintrc.cjs
  client/src/apis/axios/client.ts
  client/src/apis/goalRoom.ts
  client/src/components/_common/dialog/dialog.tsx
  client/src/components/_common/navBar/NavBar.styles.ts
  client/src/components/_common/spinner/Spinner.styles.ts
  client/src/components/_common/spinner/Spinner.tsx
  client/src/components/_providers/GoalRoomDashboardProvider.tsx
  client/src/components/goalRoomCreatePage/createGoalRoomForm/CreateGoalRoomForm.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomCertificationFeed/GoalRoomCertificationFeed.styles.ts
  client/src/components/goalRoomDahsboardPage/goalRoomCertificationFeed/GoalRoomCertificationFeed.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomCertificationFeed/certificationFeedModal/CertificationFeedModal.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomCertificationFeed/certificationFeedModal/CertificationModal.styles.ts
  client/src/components/goalRoomDahsboardPage/goalRoomDahsboardTodo/GoalRoomDashboardTodo.styles.ts
  client/src/components/goalRoomDahsboardPage/goalRoomDahsboardTodo/GoalRoomDashboardTodo.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomDahsboardTodo/todoModal/NewTodoForm.styles.ts
  client/src/components/goalRoomDahsboardPage/goalRoomDahsboardTodo/todoModal/NewTodoForm.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomDahsboardTodo/todoModal/TodoModal.styles.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomDahsboardTodo/todoModal/TodoModal.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomDashboardContent/GoalRoomDashboardContent.tsx
  client/src/constants/goalRoom/regex.ts
  client/src/context/goalRoomDashboardContext.ts
  client/src/hooks/_common/useValidateInput.ts
  client/src/hooks/goalRoom/.gitkeep
  client/src/hooks/goalRoom/useNewTodoFormValidation.ts
  client/src/hooks/queries/goalRoom.ts
  client/src/mocks/fixtures/goalRoom.ts
  client/src/mocks/handlers/goalRoomHander.ts
  client/src/myTypes/_common/dashboard.ts
  client/src/myTypes/goalRoom/internal.ts
  client/src/myTypes/goalRoom/remote.ts
  client/src/pages/goalRoomDashboardPage/GoalRoomDashboardPage.tsx
  client/src/styles/animations.ts
  client/src/styles/theme.ts
  client/src/tests/utilTests/removeDashesFromStr.test.ts
  client/src/utils/_common/removeDashesFromStr.ts
Labels: feature 🔅, FE 👨‍👨‍👧

#62 [feat/CK-129] 오류해결 & 통합한다
  client/src/App.tsx
  client/src/apis/goalRoom.ts
  client/src/apis/roadmap.ts
  client/src/components/loginPage/loginForm/LoginForm.tsx
  client/src/hooks/queries/goalRoom.ts
  client/src/hooks/queries/roadmap.ts
  client/src/hooks/queries/user.ts
Labels: feature 🔅, FE 👨‍👨‍👧

#48 [feat/CK-22,76] 사용자가 참가한 골룸 목록 조회와 단일 조회(인증 피드 조회)를 구현한다
  backend/kirikiri/src/docs/asciidoc/goalroom.adoc
  backend/kirikiri/src/main/java/co/kirikiri/controller/GoalRoomController.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoom.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomMember.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomMembers.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomPendingMember.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomPendingMembers.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomRoadmapNodes.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomToDo.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomToDos.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/vo/GoalRoomTodoContent.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomQueryRepository.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomQueryRepositoryImpl.java
  backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomReadService.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/goalroom/GoalRoomStatusTypeDto.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/goalroom/request/GoalRoomStatusTypeRequest.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/goalroom/response/CheckFeedResponse.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/goalroom/response/GoalRoomRoadmapNodeResponse.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/goalroom/response/GoalRoomRoadmapNodesResponse.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/goalroom/response/GoalRoomTodoResponse.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/member/response/MemberGoalRoomForListResponse.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/member/response/MemberGoalRoomResponse.java
  backend/kirikiri/src/main/java/co/kirikiri/service/mapper/GoalRoomMapper.java
  backend/kirikiri/src/test/java/co/kirikiri/controller/GoalRoomReadApiTest.java
  backend/kirikiri/src/test/java/co/kirikiri/domain/goalroom/GoalRoomTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomReadIntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/goalroom/GoalRoomRepositoryTest.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/roadmap/RoadmapRepositoryTest.java
  backend/kirikiri/src/test/java/co/kirikiri/service/GoalRoomCreateServiceTest.java
  backend/kirikiri/src/test/java/co/kirikiri/service/GoalRoomReadServiceTest.java
Labels: feature 🔅, BE 👨‍👩‍👧‍👦

#50 [feat/CK-122] 토스트 메세지 시스템을 구현한다
  client/src/App.tsx
  client/src/components/_common/toastProvider/ToastProvider.styles.ts
  client/src/components/_common/toastProvider/ToastProvider.tsx
  client/src/hooks/_common/useToast.ts
  client/src/hooks/queries/user.ts
  client/src/mocks/handlers/userHandler.ts
  client/src/myTypes/_common/toast.ts
  client/src/styles/theme.ts
Labels: feature 🔅, FE 👨‍👨‍👧

#63 [feat/CK-115] 골룸 투두리스트에 대한 전체 조회 및 투두리스트에 대한 체크 기능을 구현한다
  backend/kirikiri/src/docs/asciidoc/goalroom.adoc
  backend/kirikiri/src/main/java/co/kirikiri/controller/GlobalExceptionHandler.java
  backend/kirikiri/src/main/java/co/kirikiri/controller/GoalRoomController.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoom.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomToDoCheck.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomToDos.java
  backend/kirikiri/src/main/java/co/kirikiri/exception/ForbiddenException.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomQueryRepository.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomQueryRepositoryImpl.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomToDoCheckRepository.java
  backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomCreateService.java
  backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomReadService.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/goalroom/response/GoalRoomToDoCheckResponse.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/goalroom/response/GoalRoomTodoResponse.java
  backend/kirikiri/src/main/java/co/kirikiri/service/mapper/GoalRoomMapper.java
  backend/kirikiri/src/test/java/co/kirikiri/controller/GoalRoomCreateApiTest.java
  backend/kirikiri/src/test/java/co/kirikiri/controller/GoalRoomReadApiTest.java
  backend/kirikiri/src/test/java/co/kirikiri/domain/goalroom/GoalRoomToDosTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomCreateIntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomReadIntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/goalroom/GoalRoomRepositoryTest.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/goalroom/GoalRoomToDoCheckRepositoryTest.java
  backend/kirikiri/src/test/java/co/kirikiri/service/GoalRoomCreateServiceTest.java
  backend/kirikiri/src/test/java/co/kirikiri/service/GoalRoomReadServiceTest.java
Labels: feature 🔅, BE 👨‍👩‍👧‍👦

#64 fix: 시작하지 않은 골룸 페이지 진입 시 인증 피드를 받아오지 못하는 버그 수정 및 사용자 골룸 조회 테스트 복원
  backend/kirikiri/src/docs/asciidoc/goalroom.adoc
  backend/kirikiri/src/main/java/co/kirikiri/domain/ImageDirType.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoom.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomRoadmapNodes.java
  backend/kirikiri/src/main/java/co/kirikiri/service/FilePathRandomGenerator.java
  backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomCreateService.java
  backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomReadService.java
  backend/kirikiri/src/main/java/co/kirikiri/service/mapper/GoalRoomMapper.java
  backend/kirikiri/src/test/java/co/kirikiri/domain/goalroom/GoalRoomRoadmapNodesTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomReadIntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/goalroom/CheckFeedRepositoryTest.java
Labels: fix ⚒️, BE 👨‍👩‍👧‍👦

#65 [feat/CK-132] 각종 통신 에러 해결 및 투두리스트 변경점 대응 및 웹 접근성 향상
  client/src/App.tsx
  client/src/apis/goalRoom.ts
  client/src/apis/user.ts
  client/src/components/_common/navBar/NavBar.styles.ts
  client/src/components/_common/navBar/NavBar.tsx
  client/src/components/_common/roadmapItem/RoadmapItem.tsx
  client/src/components/_common/toastProvider/ToastProvider.tsx
  client/src/components/_providers/UserInfoProvider.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomDahsboardTodo/singleTodo/SingleTodo.tsx
  client/src/components/goalRoomListPage/goalRoomList/GoalRoomList.tsx
  client/src/components/loginPage/loginOptions/LoginOptions.tsx
  client/src/components/roadmapListPage/categories/Categories.styles.ts
  client/src/components/roadmapListPage/categories/Categories.tsx
  client/src/components/roadmapListPage/roadmapList/RoadmapList.tsx
  client/src/components/roadmapListPage/roadmapListView/RoadmapListView.tsx
  client/src/components/signUpPage/SignUpForm.tsx
  client/src/hooks/queries/goalRoom.ts
  client/src/hooks/queries/user.ts
  client/src/hooks/roadmap/useSelectCategory.ts
  client/src/hooks/user/.gitkeep
  client/src/hooks/user/useValidationCheck.ts
  client/src/mocks/fixtures/goalRoom.ts
  client/src/myTypes/_common/user.ts
  client/src/myTypes/goalRoom/internal.ts
  client/src/myTypes/goalRoom/remote.ts
  client/src/myTypes/user/remote.ts
  client/src/pages/myPage/MyPage.tsx
  client/src/tests/utilTests/isValidUserInfo.test.ts
  client/src/utils/user/isValidUserInfo.ts
Labels: feature 🔅, FE 👨‍👨‍👧

#67 fix: 사용자 골룸 단일 조회 버그 fix
  backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomReadService.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomReadIntegrationTest.java
Labels: fix ⚒️, BE 👨‍👩‍👧‍👦

#66 [feat/CK-130] 페이지 라우팅과 잔여 서버 연결을 처리한다
  client/src/apis/goalRoom.ts
  client/src/apis/roadmap.ts
  client/src/components/_common/button/Button.tsx
  client/src/components/_common/dialog/dialog.tsx
  client/src/components/_common/roadmapItem/RoadmapItem.tsx
  client/src/components/goalRoomCreatePage/createGoalRoom/CreateGoalRoom.tsx
  client/src/components/goalRoomDetailPage/.gitkeep
  client/src/components/goalRoomListPage/goalRoomDetail/GoalRoomDetailDialog.tsx
  client/src/components/goalRoomListPage/goalRoomDetail/GoalRoomDetailDialogContent.tsx
  client/src/components/goalRoomListPage/goalRoomDetail/goalRoomDetailDialog.styles.ts
  client/src/components/goalRoomListPage/goalRoomList/GoalRoomItem.tsx
  client/src/components/goalRoomListPage/goalRoomList/GoalRoomList.tsx
  client/src/components/goalRoomListPage/goalRoomList/goalRoomList.styles.ts
  client/src/components/roadmapCreatePage/roadmap/RoadmapItem.tsx
  client/src/components/roadmapCreatePage/roadmap/roadmap.styles.ts
  client/src/components/roadmapCreatePage/roadmapCreateForm/RoadmapCreateForm.tsx
  client/src/components/roadmapCreatePage/roadmapCreateForm/roadmapCreateForm.styles.ts
  client/src/components/roadmapDetailPage/roadmapDetail/RoadmapDetail.tsx
  client/src/components/roadmapListPage/roadmapList/RoadmapList.styles.ts
  client/src/components/roadmapListPage/roadmapList/RoadmapList.tsx
  client/src/hooks/queries/goalRoom.ts
  client/src/hooks/queries/roadmap.ts
  client/src/hooks/roadmap/useCollectRoadmapData.ts
  client/src/mocks/fixtures/roadmapList.ts
  client/src/myTypes/goalRoom/internal.ts
  client/src/myTypes/goalRoom/remote.ts
  client/src/myTypes/roadmap/internal.ts
  client/src/myTypes/roadmap/remote.ts
Labels: fix ⚒️, feature 🔅, FE 👨‍👨‍👧

#68 Feature/ck 135
  client/src/App.tsx
  client/src/components/_common/roadmapItem/RoadmapItem.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomCertificationFeed/GoalRoomCertificationFeed.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomDashboardHeader/GoalRoomDashboardHeader.tsx
  client/src/hooks/queries/goalRoom.ts
  client/src/mocks/fixtures/goalRoom.ts
  client/src/myTypes/goalRoom/remote.ts
  client/src/pages/goalRoomDashboardPage/GoalRoomDashboardPage.tsx
Labels: fix ⚒️, FE 👨‍👨‍👧

#69 feat: 통신 에러 해결
  client/src/apis/goalRoom.ts
  client/src/components/goalRoomListPage/goalRoomDetail/GoalRoomDetailDialog.tsx
  client/src/components/goalRoomListPage/goalRoomList/GoalRoomItem.tsx
  client/src/components/goalRoomListPage/goalRoomList/GoalRoomList.tsx
  client/src/components/roadmapListPage/roadmapList/RoadmapList.styles.ts
  client/src/hooks/queries/goalRoom.ts
  client/src/index.tsx
  client/src/myTypes/goalRoom/internal.ts
  client/src/myTypes/goalRoom/remote.ts
  client/src/pages/goalRoomListPage/GoalRoomListPage.tsx
Labels: feature 🔅, FE 👨‍👨‍👧

#42 [feat/CK-71] 골룸을 나가는 기능을 구현한다
  .gitmodules
  backend/kirikiri/src/docs/asciidoc/goalroom.adoc
  backend/kirikiri/src/main/java/co/kirikiri/controller/GoalRoomController.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/BaseGoalRoomMember.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoom.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomMember.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomMembers.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomPendingMember.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomPendingMembers.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomMemberRepository.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomQueryRepository.java
  backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomCreateService.java
  backend/kirikiri/src/main/java/co/kirikiri/service/mapper/GoalRoomMapper.java
  backend/kirikiri/src/test/java/co/kirikiri/controller/GoalRoomCreateApiTest.java
  backend/kirikiri/src/test/java/co/kirikiri/controller/GoalRoomReadApiTest.java
  backend/kirikiri/src/test/java/co/kirikiri/domain/goalroom/GoalRoomMemberTest.java
  backend/kirikiri/src/test/java/co/kirikiri/domain/goalroom/GoalRoomMembersTest.java
  backend/kirikiri/src/test/java/co/kirikiri/domain/goalroom/GoalRoomPendingMemberTest.java
  backend/kirikiri/src/test/java/co/kirikiri/domain/goalroom/GoalRoomPendingMembersTest.java
  backend/kirikiri/src/test/java/co/kirikiri/domain/goalroom/GoalRoomTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomCreateIntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomReadIntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapReadIntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/service/GoalRoomCreateServiceTest.java
  backend/kirikiri/src/test/java/co/kirikiri/service/GoalRoomServiceIntegrationTest.java
Labels: feature 🔅, BE 👨‍👩‍👧‍👦

#98 [feat/CK-140] 골룸 생성이 되지 않는 버그를 해결한다
  client/src/apis/goalRoom.ts
  client/src/components/_common/roadmapItem/RoadmapItem.tsx
  client/src/components/goalRoomCreatePage/createGoalRoomForm/CreateGoalRoomForm.tsx
  client/src/hooks/_common/useFormInput.ts
  client/src/hooks/queries/goalRoom.ts
Labels: fix ⚒️, feature 🔅, FE 👨‍👨‍👧

#13 [feat/CK-51] Github Action을 통해 CI를 구축한다
  .github/workflows/backend-pull-request-workflow.yml
  backend/kirikiri/build.gradle
Labels: feature 🔅, BE 👨‍👩‍👧‍👦

#106 [feat/CK-65] 골룸 사용자 목록 조회 API를 개발한다
  backend/kirikiri/src/docs/asciidoc/goalroom.adoc
  backend/kirikiri/src/docs/asciidoc/member.adoc
  backend/kirikiri/src/main/java/co/kirikiri/controller/GoalRoomController.java
  backend/kirikiri/src/main/java/co/kirikiri/controller/RoadmapController.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/BaseCreatedTimeEntity.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/member/Member.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/dto/GoalRoomLastValueDto.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/dto/RoadmapLastValueDto.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/dto/RoadmapReviewLastValueDto.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomMemberQueryRepository.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomMemberQueryRepositoryImpl.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomMemberRepository.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomQueryRepository.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomQueryRepositoryImpl.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/dto/GoalRoomMemberSortType.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/roadmap/RoadmapQueryRepository.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/roadmap/RoadmapQueryRepositoryImpl.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/roadmap/RoadmapReviewQueryRepository.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/roadmap/RoadmapReviewQueryRepositoryImpl.java
  backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomReadService.java
  backend/kirikiri/src/main/java/co/kirikiri/service/RoadmapReadService.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/CustomReviewScrollRequest.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/CustomScrollRequest.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/goalroom/GoalRoomMemberSortTypeDto.java
  backend/kirikiri/src/test/java/co/kirikiri/controller/GoalRoomReadApiTest.java
  backend/kirikiri/src/test/java/co/kirikiri/controller/RoadmapReadApiTest.java
  backend/kirikiri/src/test/java/co/kirikiri/domain/goalroom/GoalRoomMemberTest.java
  backend/kirikiri/src/test/java/co/kirikiri/domain/goalroom/GoalRoomMembersTest.java
  backend/kirikiri/src/test/java/co/kirikiri/domain/goalroom/GoalRoomPendingMemberTest.java
  backend/kirikiri/src/test/java/co/kirikiri/domain/goalroom/GoalRoomPendingMembersTest.java
  backend/kirikiri/src/test/java/co/kirikiri/domain/goalroom/GoalRoomTest.java
  backend/kirikiri/src/test/java/co/kirikiri/domain/roadmap/RoadmapContentTest.java
  backend/kirikiri/src/test/java/co/kirikiri/domain/roadmap/RoadmapReviewTest.java
  backend/kirikiri/src/test/java/co/kirikiri/domain/roadmap/RoadmapTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomReadIntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapCreateIntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapReadIntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/auth/RefreshTokenRepositoryTest.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/goalroom/GoalRoomMemberRepositoryTest.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/goalroom/GoalRoomPendingMemberRepositoryTest.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/goalroom/GoalRoomRepositoryTest.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/goalroom/GoalRoomToDoCheckRepositoryTest.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/roadmap/RoadmapContentRepositoryTest.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/roadmap/RoadmapRepositoryTest.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/roadmap/RoadmapReviewRepositoryTest.java
  backend/kirikiri/src/test/java/co/kirikiri/service/AuthServiceTest.java
  backend/kirikiri/src/test/java/co/kirikiri/service/GoalRoomCreateServiceTest.java
  backend/kirikiri/src/test/java/co/kirikiri/service/GoalRoomReadServiceTest.java
  backend/kirikiri/src/test/java/co/kirikiri/service/GoalRoomServiceIntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/service/MemberServiceTest.java
  backend/kirikiri/src/test/java/co/kirikiri/service/RoadmapCreateServiceTest.java
  backend/kirikiri/src/test/java/co/kirikiri/service/RoadmapReadServiceTest.java
Labels: feature 🔅, BE 👨‍👩‍👧‍👦

#102 [feat/CK-149] 골룸 인증피드 내부 전체 인증피드 도출 로직을 구현한다
  client/src/apis/goalRoom.ts
  client/src/components/goalRoomDahsboardPage/goalRoomCertificationFeed/certificationFeedModal/CertificationFeedModal.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomCertificationFeed/certificationFeedModal/CertificationModal.styles.ts
  client/src/constants/@queryKeys/queryKeys.ts
  client/src/hooks/queries/goalRoom.ts
  client/src/myTypes/goalRoom/remote.ts
Labels: feature 🔅, FE 👨‍👨‍👧

#104 [feat/CK-150] 회원가입 프로세스 UX 를 개선한다.
  client/src/components/_common/toastProvider/ToastProvider.tsx
  client/src/constants/user/.gitkeep
  client/src/constants/user/regex.ts
  client/src/hooks/_common/useValidateInput.ts
  client/src/hooks/queries/user.ts
  client/src/hooks/user/useSignUpFormValidation.ts
Labels: feature 🔅, FE 👨‍👨‍👧

#112 [feat/CK-152] 로드맵 목록 조회에 무한 스크롤을 적용한다. 골룸 대시보드에 랭킹을 추가한다.
  client/src/apis/goalRoom.ts
  client/src/apis/roadmap.ts
  client/src/assets/images/podium.png
  client/src/components/goalRoomDahsboardPage/goalRoomDashboardCalender/GoalRoomDashboardCalender.styles.ts
  client/src/components/goalRoomDahsboardPage/goalRoomDashboardCalender/GoalRoomDashboardCalender.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomDashboardContent/GoalRoomDashboardContent.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomUserRanking/GoalRoomUserRanking.styles.ts
  client/src/components/goalRoomDahsboardPage/goalRoomUserRanking/GoalRoomUserRanking.tsx
  client/src/components/roadmapListPage/roadmapList/RoadmapList.styles.ts
  client/src/components/roadmapListPage/roadmapList/RoadmapList.tsx
  client/src/components/roadmapListPage/roadmapListView/RoadmapListView.tsx
  client/src/constants/@queryKeys/queryKeys.ts
  client/src/hooks/_common/useInfiniteScroll.ts
  client/src/hooks/_common/useIntersection.ts
  client/src/hooks/queries/goalRoom.ts
  client/src/hooks/queries/roadmap.ts
  client/src/myTypes/goalRoom/remote.ts
  client/src/myTypes/roadmap/remote.ts
  client/src/pages/goalRoomListPage/GoalRoomListPage.tsx
  client/src/pages/roadmapDetailPage/RoadmapDetailPage.tsx
  client/src/styles/animations.ts
Labels: feature 🔅, FE 👨‍👨‍👧

#114 [feat/CK-147] 골룸 생성 페이지 고도화 및 유효성 검사를 구현한다
  client/src/components/_common/InputField/InputField.styles.ts
  client/src/components/_common/InputField/InputField.tsx
  client/src/components/goalRoomCreatePage/createGoalRoomForm/CreateGoalRoomForm.styles.ts
  client/src/components/goalRoomCreatePage/createGoalRoomForm/CreateGoalRoomForm.tsx
  client/src/components/goalRoomCreatePage/createGoalRoomForm/createGoalRoomValidations.ts
  client/src/components/goalRoomCreatePage/inputField/InputField.styles.ts
  client/src/components/goalRoomCreatePage/inputField/InputField.tsx
  client/src/components/goalRoomCreatePage/nodeSection/NodeSection.styles.ts
  client/src/components/goalRoomCreatePage/nodeSection/NodeSection.tsx
  client/src/components/goalRoomCreatePage/pageSection/PageSection.styles.ts
  client/src/components/goalRoomCreatePage/todoListSection/TodoListSection.styles.ts
  client/src/components/goalRoomCreatePage/todoListSection/TodoListSection.tsx
  client/src/constants/goalRoom/goalRoomValidation.ts
  client/src/hooks/_common/useFormInput.ts
  client/src/tests/utilTests/isCurrentOrFutureDate.test.ts
  client/src/tests/utilTests/isEmptyString.test.ts
  client/src/tests/utilTests/isNumeric.test.ts
  client/src/tests/utilTests/isValidMaxLength.test.ts
  client/src/tests/utilTests/isValidMaxValue.test.ts
  client/src/tests/utilTests/transformDateStringsIn.test.ts
  client/src/utils/_common/isCurrentOrFutureDate.ts
  client/src/utils/_common/isEmptyString.ts
  client/src/utils/_common/isNumeric.ts
  client/src/utils/_common/isValidMaxLength.ts
  client/src/utils/_common/isValidMaxValue.ts
  client/src/utils/_common/transformDateStringsIn.ts
Labels: feature 🔅, FE 👨‍👨‍👧

#110 [feat/CK-151] 골룸리스트의 오류를 해결한다
  client/src/apis/goalRoom.ts
  client/src/components/goalRoomListPage/goalRoomList/GoalRoomFilter.tsx
  client/src/components/goalRoomListPage/goalRoomList/GoalRoomList.tsx
  client/src/components/goalRoomListPage/goalRoomList/goalRoomList.styles.ts
  client/src/constants/goalRoom/goalRoomFilter.ts
  client/src/hooks/queries/goalRoom.ts
  client/src/myTypes/_common/global.d.ts
  client/src/myTypes/goalRoom/remote.ts
Labels: fix ⚒️, feature 🔅, FE 👨‍👨‍👧

#107 [feat/CK-151] Selectbox의 오류를 해결한다
  client/src/components/roadmapCreatePage/difficulty/Difficulty.tsx
  client/src/components/roadmapCreatePage/difficulty/difficulty.styles.ts
  client/src/components/roadmapCreatePage/selector/SelectBox.tsx
  client/src/hooks/roadmap/useCollectRoadmapData.ts
  client/src/myTypes/_common/select.ts
Labels: feature 🔅, FE 👨‍👨‍👧

#117 [Fix/CK-165] 골룸 참여자 조회 시 골룸의 상태에 상관없이 조회 가능하도록 수정한다
  backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomPendingMemberQueryRepository.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomPendingMemberQueryRepositoryImpl.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomPendingMemberRepository.java
  backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomReadService.java
  backend/kirikiri/src/main/java/co/kirikiri/service/mapper/GoalRoomMapper.java
  backend/kirikiri/src/test/java/co/kirikiri/controller/GoalRoomReadApiTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomReadIntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/goalroom/GoalRoomPendingMemberRepositoryTest.java
  backend/kirikiri/src/test/java/co/kirikiri/service/GoalRoomReadServiceTest.java
Labels: fix ⚒️, BE 👨‍👩‍👧‍👦

#119 [feat/CK-163] 로그인 라우팅 처리 로직 수정 및 뒤로가기 버튼 위치를 조정한다
  client/src/components/loginPage/loginContent/LoginContent.styles.ts
  client/src/components/loginPage/loginContent/LoginContent.tsx
  client/src/components/loginPage/loginForm/LoginForm.tsx
  client/src/hooks/queries/user.ts
Labels: feature 🔅, FE 👨‍👨‍👧

#115 [feat/CK-160] 골룸 전체 참여자 모달을 구현한다
  client/src/components/goalRoomDahsboardPage/goalRoomDashboardHeader/GoalRoomDashboardHeader.styles.ts
  client/src/components/goalRoomDahsboardPage/goalRoomDashboardHeader/GoalRoomDashboardHeader.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomDashboardHeader/goalRoomParticipantsListModal/GoalRoomParticipantsListModal.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomDashboardHeader/goalRoomParticipantsListModal/GoalRoomParticipantsModal.styles.ts
Labels: feature 🔅, FE 👨‍👨‍👧

#120 [feat/CK-166] 골룸 리스트 페이지 버그 수정 및 무한 스크롤을 구현한다
  client/src/apis/goalRoom.ts
  client/src/components/_common/wavyLoading/WavyLoading.styles.ts
  client/src/components/_common/wavyLoading/WavyLoading.tsx
  client/src/components/goalRoomListPage/goalRoomDetail/GoalRoomDetailDialog.tsx
  client/src/components/goalRoomListPage/goalRoomList/GoalRoomList.tsx
  client/src/components/goalRoomListPage/goalRoomList/goalRoomList.styles.ts
  client/src/components/roadmapListPage/roadmapList/RoadmapList.styles.ts
  client/src/components/roadmapListPage/roadmapList/RoadmapList.tsx
  client/src/constants/@queryKeys/queryKeys.ts
  client/src/hooks/queries/goalRoom.ts
  client/src/myTypes/goalRoom/remote.ts
  client/src/pages/goalRoomCreatePage/GoalRoomCreatePage.tsx
Labels: feature 🔅, FE 👨‍👨‍👧

#122 [feat/CK-168] 로드맵 생성부분의 변경된 api를 반영한다 ( 사진추가 기능 )
  client/src/apis/roadmap.ts
  client/src/components/icons/svgIcons.tsx
  client/src/components/roadmapCreatePage/roadmap/RoadmapItem.tsx
  client/src/components/roadmapCreatePage/roadmap/roadmap.styles.ts
  client/src/components/roadmapCreatePage/roadmapCreateForm/RoadmapCreateForm.tsx
  client/src/components/roadmapCreatePage/roadmapCreateForm/roadmapCreateForm.styles.ts
  client/src/hooks/_common/useUploadImage.ts
  client/src/hooks/queries/roadmap.ts
  client/src/hooks/roadmap/useCollectRoadmapData.ts
  client/src/myTypes/roadmap/internal.ts
  client/src/myTypes/roadmap/remote.ts
Labels: feature 🔅, FE 👨‍👨‍👧

#118 [feat/CK-164] 네브바 고도화 및 로그아웃 버튼을 활성화한다
  client/src/components/_common/navBar/NavBar.styles.ts
  client/src/components/_common/navBar/NavBar.tsx
  client/src/components/_common/pageLayout/PageLayout.styles.ts
  client/src/components/_common/pageLayout/PageLayout.tsx
  client/src/hooks/queries/user.ts
Labels: feature 🔅, FE 👨‍👨‍👧

#121 [feat/CK-167] 골룸 기능들을 고도화 한다
  client/src/apis/goalRoom.ts
  client/src/components/_common/navBar/NavBar.tsx
  client/src/components/_common/pageLayout/PageLayout.styles.ts
  client/src/components/goalRoomDahsboardPage/goalRoomCertificationFeed/GoalRoomCertificationFeed.styles.ts
  client/src/components/goalRoomDahsboardPage/goalRoomCertificationFeed/GoalRoomCertificationFeed.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomCertificationFeed/certificationFeedModal/CertificationFeedModal.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomDahsboardTodo/GoalRoomDashboardTodo.styles.ts
  client/src/components/goalRoomDahsboardPage/goalRoomDahsboardTodo/GoalRoomDashboardTodo.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomDahsboardTodo/todoModal/TodoModal.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomDashboardChat/GoalRoomDashboardChat.styles.ts
  client/src/components/goalRoomDahsboardPage/goalRoomDashboardChat/GoalRoomDashboardChat.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomDashboardContent/GoalRoomDashboardContent.styles.ts
  client/src/components/goalRoomDahsboardPage/goalRoomDashboardContent/GoalRoomDashboardContent.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomDashboardHeader/GoalRoomDashboardHeader.styles.ts
  client/src/components/goalRoomDahsboardPage/goalRoomDashboardHeader/GoalRoomDashboardHeader.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomDashboardHeader/goalRoomParticipantsListModal/GoalRoomParticipantsListModal.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomUserRanking/GoalRoomUserRanking.styles.ts
  client/src/components/goalRoomDahsboardPage/goalRoomUserRanking/GoalRoomUserRanking.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomUserRanking/goalRoomRankingModal/GoalRoomRankingModal.styles.ts
  client/src/components/goalRoomDahsboardPage/goalRoomUserRanking/goalRoomRankingModal/GoalRoomRankingModal.tsx
  client/src/components/goalRoomListPage/goalRoomDetail/goalRoomDetailDialog.styles.ts
  client/src/components/myPage/myPageUserInfo/MyPageUserInfo.tsx
  client/src/constants/@queryKeys/queryKeys.ts
  client/src/hooks/_common/useValidateInput.ts
  client/src/hooks/queries/goalRoom.ts
  client/src/styles/theme.ts
  client/src/tests/utilTests/isTodayOrAfter.test.ts
  client/src/utils/_common/isTodayOrAfter.ts
Labels: FE 👨‍👨‍👧

#123 [feat/CK-170] 전반적인 ux 를 개선한다
  client/.eslintrc.cjs
  client/public/index.html
  client/public/logo.ico
  client/src/App.tsx
  client/src/apis/roadmap.ts
  client/src/assets/images/elephant.png
  client/src/components/_common/roadmapItem/RoadmapItem.styles.ts
  client/src/components/_common/roadmapItem/RoadmapItem.tsx
  client/src/components/goalRoomCreatePage/createGoalRoomForm/CreateGoalRoomForm.tsx
  client/src/components/loginPage/loginContent/LoginContent.styles.ts
  client/src/components/loginPage/loginContent/LoginContent.tsx
  client/src/components/myPage/myPageContent/MyPageContent.tsx
  client/src/components/myPage/myPageGoalRoomTab/MyPageGoalRoomTab.styles.ts
  client/src/components/myPage/myPageGoalRoomTab/MyPageGoalRoomTab.tsx
  client/src/components/myPage/myPageRoadmapTab/MyPageRoadmapTab.tsx
  client/src/components/myPage/myPageRoadmapTab/MyPageRoadmapTap.styles.ts
  client/src/components/roadmapDetailPage/roadmapDetail/RoadmapDetail.tsx
  client/src/components/roadmapListPage/roadmapListView/RoadmapListView.styles.ts
  client/src/components/roadmapListPage/roadmapListView/RoadmapListView.tsx
  client/src/constants/@queryKeys/queryKeys.ts
  client/src/constants/roadmap/difficulty.ts
  client/src/hooks/queries/roadmap.ts
  client/src/hooks/queries/user.ts
  client/src/hooks/roadmap/useCollectRoadmapData.ts
  client/src/myTypes/roadmap/internal.ts
  client/src/pages/loginPage/LoginPage.styles.ts
  client/src/pages/loginPage/LoginPage.tsx
  client/src/pages/mainPage/.gitkeep
  client/src/pages/mainPage/MainPage.styles.ts
  client/src/pages/mainPage/MainPage.tsx
  client/src/styles/GlobalStyle.tsx
  client/src/styles/animations.ts
  client/src/tests/utilTests/formatDate.test.ts
  client/src/utils/_common/formatDate.ts
  client/webpack.common.js
Labels: feature 🔅, FE 👨‍👨‍👧

#128 [feat/CK-172] 골룸 목록 정렬 구현 및 스타일 고도화를 진행한다
  client/src/apis/goalRoom.ts
  client/src/components/goalRoomListPage/goalRoomDetail/goalRoomDetailDialog.styles.ts
  client/src/components/goalRoomListPage/goalRoomList/GoalRoomFilter.tsx
  client/src/components/goalRoomListPage/goalRoomList/GoalRoomList.tsx
  client/src/components/goalRoomListPage/goalRoomList/goalRoomList.styles.ts
  client/src/components/roadmapCreatePage/selector/SelectBox.tsx
  client/src/constants/goalRoom/goalRoomFilter.ts
  client/src/myTypes/goalRoom/remote.ts
Labels: feature 🔅, FE 👨‍👨‍👧

#129 [feat/CK-177] 골룸 생성 유효성 검사를 고도화한다
  client/.eslintrc.cjs
  client/src/components/goalRoomCreatePage/createGoalRoomForm/CreateGoalRoomForm.tsx
  client/src/components/goalRoomCreatePage/createGoalRoomForm/createGoalRoomValidations.ts
  client/src/constants/goalRoom/goalRoomValidation.ts
  client/src/hooks/_common/useFormInput.ts
Labels: feature 🔅, FE 👨‍👨‍👧

#127 [feat/CK-171] 로드맵 확인하기를 구현한다 & 로드맵 리스트의 UI를 변경한다
  client/src/apis/goalRoom.ts
  client/src/components/_common/roadmapItem/RoadmapItem.styles.ts
  client/src/components/roadmapCreatePage/roadmap/RoadmapItem.tsx
  client/src/components/roadmapDetailPage/openNodeListButton/OpenNodeListButton.styles.ts
  client/src/components/roadmapDetailPage/openNodeListButton/OpenNodeListButton.tsx
  client/src/components/roadmapDetailPage/roadmapDetail/RoadmapDetail.styles.ts
  client/src/components/roadmapDetailPage/roadmapDetail/RoadmapDetail.tsx
  client/src/components/roadmapDetailPage/roadmapNodeList/RoadmapNodeList.tsx
  client/src/components/roadmapDetailPage/roadmapNodeList/roadmapNodeList.styles.ts
  client/src/components/roadmapListPage/roadmapList/RoadmapList.styles.ts
  client/src/components/roadmapListPage/roadmapList/RoadmapList.tsx
  client/src/hooks/_common/useUploadImage.ts
  client/src/hooks/queries/goalRoom.ts
  client/src/hooks/roadmap/useCollectRoadmapData.ts
  client/src/myTypes/goalRoom/internal.ts
  client/src/myTypes/goalRoom/remote.ts
Labels: feature 🔅, enhancement, FE 👨‍👨‍👧

#133 [Release] CK Backend v1.1.2
  backend/kirikiri/src/main/java/co/kirikiri/persistence/dto/RoadmapSearchDto.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/fixture/RoadmapAPIFixture.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/roadmap/RoadmapRepositoryTest.java
Labels: BE 👨‍👩‍👧‍👦

#134 [hotfix/CK-178] 4차 데모데이 전 버그수정
  client/src/App.tsx
  client/src/components/_common/roadmapItem/RoadmapItem.styles.ts
  client/src/components/_common/roadmapItem/RoadmapItem.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomDahsboardRoadmap/GoalRoomDashboardRoadmap.styles.ts
  client/src/components/goalRoomDahsboardPage/goalRoomDahsboardRoadmap/GoalRoomDashboardRoadmap.tsx
  client/src/components/goalRoomListPage/goalRoomDetail/goalRoomDetailDialog.styles.ts
  client/src/components/roadmapCreatePage/category/Category.tsx
  client/src/components/roadmapCreatePage/mainText/MainText.tsx
  client/src/components/roadmapCreatePage/selector/SelectBox.tsx
  client/src/components/roadmapListPage/roadmapSearch/RoadmapSearch.tsx
  client/src/components/roadmapListPage/roadmapSearch/RoadmapSearchResult.tsx
  client/src/constants/roadmap/category.ts
  client/src/hooks/queries/roadmap.ts
  client/src/hooks/roadmap/useCollectRoadmapData.ts
  client/src/myTypes/_common/select.ts
Labels: fix ⚒️, feature 🔅, FE 👨‍👨‍👧

#136 [Release] CK Frontend v1.0.1
  client/src/apis/axios/client.ts
  client/src/components/goalRoomCreatePage/createGoalRoom/CreateGoalRoom.tsx
  client/src/components/goalRoomCreatePage/nodeSection/NodeSection.styles.ts
  client/src/components/roadmapCreatePage/roadmap/RoadmapItem.tsx
  client/src/hooks/queries/roadmap.ts
  client/src/hooks/roadmap/useCollectRoadmapData.ts
Labels: FE 👨‍👨‍👧
