Repository woowacourse-teams/2023-co-kirikiri, pull requests merged in 2023-07, with the labels that each got.

#2 [feat/CK-19] 회원가입 API를 구현한다
  backend/kirikiri/build.gradle
  backend/kirikiri/src/docs/asciidoc/member.adoc
  backend/kirikiri/src/docs/asciidoc/overview.adoc
  backend/kirikiri/src/main/java/co/kirikiri/controller/GlobalExceptionHandler.java
  backend/kirikiri/src/main/java/co/kirikiri/controller/MemberController.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/member/Member.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/member/MemberProfile.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/member/vo/EncryptedPassword.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/member/vo/Identifier.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/member/vo/Nickname.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/member/vo/Password.java
  backend/kirikiri/src/main/java/co/kirikiri/exception/AuthenticationException.java
  backend/kirikiri/src/main/java/co/kirikiri/exception/BadRequestException.java
  backend/kirikiri/src/main/java/co/kirikiri/exception/BusinessException.java
  backend/kirikiri/src/main/java/co/kirikiri/exception/ConflictException.java
  backend/kirikiri/src/main/java/co/kirikiri/exception/ServerException.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/member/MemberProfileRepository.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/member/MemberRepository.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/ErrorResponse.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/member/GenderType.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/member/MemberJoinDto.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/member/request/MemberJoinRequest.java
  backend/kirikiri/src/main/java/co/kirikiri/service/mapper/member/MemberMapper.java
  backend/kirikiri/src/main/java/co/kirikiri/service/member/MemberService.java
  backend/kirikiri/src/main/resources/application.yml
  backend/kirikiri/src/test/java/co/kirikiri/controller/MemberControllerTest.java
  backend/kirikiri/src/test/java/co/kirikiri/controller/helper/RestDocsHelper.java
  backend/kirikiri/src/test/java/co/kirikiri/controller/helper/TestObjectMapperConfig.java
  backend/kirikiri/src/test/java/co/kirikiri/domain/member/vo/EncryptedPasswordTest.java
  backend/kirikiri/src/test/java/co/kirikiri/domain/member/vo/IdentifierTest.java
  backend/kirikiri/src/test/java/co/kirikiri/domain/member/vo/NicknameTest.java
  backend/kirikiri/src/test/java/co/kirikiri/domain/member/vo/PasswordTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/IntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/MemberIntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/RepositoryTest.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/member/MemberProfileRepositoryTest.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/member/MemberRepositoryTest.java
  backend/kirikiri/src/test/java/co/kirikiri/service/member/MemberServiceTest.java
  backend/kirikiri/src/test/resources/application.yml
Labels: feature 🔅, BE 👨‍👩‍👧‍👦

#6 [feat/CK-50] react-query boilerplate를 세팅한다
  client/.eslintrc.cjs
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/apis/axios/client.ts
  client/src/apis/user.ts
  client/src/apis/user/.gitkeep
  client/src/constants/@queryKeys/queryKeys.ts
  client/src/hooks/queries/user.ts
  client/src/index.tsx
  client/src/myTypes/_common/.gitkeep
  client/src/myTypes/goalRoom/.gitkeep
  client/src/myTypes/roadmap/.gitkeep
  client/src/myTypes/user/remote.ts
  client/src/types/_common/.gitkeep
  client/src/types/goalRoom/.gitkeep
  client/src/types/roadmap/.gitkeep
  client/src/types/user/.gitkeep
  client/tsconfig.json
  client/webpack.common.js
  client/webpack.prod.js
Labels: feature 🔅, FE 👨‍👨‍👧

#7 [feat/CK-53] 반응형 Layout의 변경된 요구사항을 반영하고 PageLayout을 구현한다
  client/src/components/_common/pageLayout/PageLayout.styles.ts
  client/src/components/_common/pageLayout/PageLayout.tsx
  client/src/components/_common/responsiveContainer/ResponsiveContainer.styles.tsx
  client/src/utils/_common/pxToVw.ts
Labels: feature 🔅, FE 👨‍👨‍👧

#5 [feat/CK-39] 로드맵 카테고리 리스트 조회 기능을 구현한다
  backend/kirikiri/src/docs/asciidoc/index.adoc
  backend/kirikiri/src/docs/asciidoc/overview.adoc
  backend/kirikiri/src/docs/asciidoc/roadmap.adoc
  backend/kirikiri/src/main/java/co/kirikiri/controller/RoadmapController.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapCategory.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/RoadmapCategoryRepository.java
  backend/kirikiri/src/main/java/co/kirikiri/service/RoadmapService.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/ErrorResponse.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/RoadmapCategoryResponse.java
  backend/kirikiri/src/main/java/co/kirikiri/service/mapper/RoadmapMapper.java
  backend/kirikiri/src/test/java/co/kirikiri/KirikiriApplicationTests.java
  backend/kirikiri/src/test/java/co/kirikiri/controller/RoadmapControllerTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapIntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/helper/IntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/service/RoadmapServiceTest.java
  backend/kirikiri/src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
  backend/kirikiri/src/test/resources/org/springframework/restdocs/templates/request-parameters.snippet
  backend/kirikiri/src/test/resources/org/springframework/restdocs/templates/response-fields.snippet
Labels: feature 🔅, BE 👨‍👩‍👧‍👦

#3 [feat/CK-18] 로드맵 목록 필터링 조회 기능을 구현한다
  backend/kirikiri/src/docs/asciidoc/index.adoc
  backend/kirikiri/src/docs/asciidoc/member.adoc
  backend/kirikiri/src/docs/asciidoc/overview.adoc
  backend/kirikiri/src/docs/asciidoc/roadmap.adoc
  backend/kirikiri/src/main/java/co/kirikiri/controller/GlobalExceptionHandler.java
  backend/kirikiri/src/main/java/co/kirikiri/controller/MemberController.java
  backend/kirikiri/src/main/java/co/kirikiri/controller/RoadmapController.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/member/Member.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/member/MemberProfile.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/member/MemberProfileImage.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/member/vo/Nickname.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/Roadmap.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapCategory.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapContent.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/dto/RoadmapFilterType.java
  backend/kirikiri/src/main/java/co/kirikiri/exception/NotFoundException.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/roadmap/RoadmapCategoryRepository.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/roadmap/RoadmapQueryRepository.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/roadmap/RoadmapQueryRepositoryImpl.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/roadmap/RoadmapRepository.java
  backend/kirikiri/src/main/java/co/kirikiri/service/MemberService.java
  backend/kirikiri/src/main/java/co/kirikiri/service/RoadmapService.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/CustomPageRequest.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/PageResponse.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/member/MemberResponse.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/roadmap/RoadmapCategoryResponse.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/roadmap/RoadmapFilterTypeDto.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/roadmap/RoadmapResponse.java
  backend/kirikiri/src/main/java/co/kirikiri/service/mapper/MemberMapper.java
  backend/kirikiri/src/main/java/co/kirikiri/service/mapper/RoadmapMapper.java
  backend/kirikiri/src/test/java/co/kirikiri/controller/MemberControllerTest.java
  backend/kirikiri/src/test/java/co/kirikiri/controller/RoadmapControllerTest.java
  backend/kirikiri/src/test/java/co/kirikiri/controller/helper/RestDocsHelper.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/IntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/MemberIntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapIntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/helper/IntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/helper/RepositoryTest.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/helper/TestEntityManagerConfig.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/member/MemberProfileRepositoryTest.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/member/MemberRepositoryTest.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/roadmap/RoadmapRepositoryTest.java
  backend/kirikiri/src/test/java/co/kirikiri/service/MemberServiceTest.java
  backend/kirikiri/src/test/java/co/kirikiri/service/RoadmapServiceTest.java
  backend/kirikiri/src/test/resources/application.yml
Labels: feature 🔅, BE 👨‍👩‍👧‍👦

#19 [feat/CK-56] NavBar 뼈대 구현 PR 내용을 반영한다
  client/src/components/_common/header/Header.styles.ts
  client/src/components/_common/header/Header.tsx
  client/src/components/_common/navBar/NavBar.styles.ts
  client/src/components/_common/navBar/NavBar.tsx
  client/src/hooks/_common/useSwitch.ts
  client/src/styles/theme.ts
Labels: feature 🔅, FE 👨‍👨‍👧

#8 [feat/CK-16] 로드맵 생성 기능을 구현한다
  backend/kirikiri/src/docs/asciidoc/overview.adoc
  backend/kirikiri/src/docs/asciidoc/roadmap.adoc
  backend/kirikiri/src/main/java/co/kirikiri/common/config/WebMvcConfig.java
  backend/kirikiri/src/main/java/co/kirikiri/controller/AuthPrincipal.java
  backend/kirikiri/src/main/java/co/kirikiri/controller/GlobalExceptionHandler.java
  backend/kirikiri/src/main/java/co/kirikiri/controller/MemberArgumentResolver.java
  backend/kirikiri/src/main/java/co/kirikiri/controller/RoadmapController.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/ImageContentType.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/member/Member.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/member/MemberProfile.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/member/MemberProfileImage.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/Roadmap.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapCategory.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapContent.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapContents.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapNode.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapNodes.java
  backend/kirikiri/src/main/java/co/kirikiri/exception/BadRequestException.java
  backend/kirikiri/src/main/java/co/kirikiri/service/RoadmapService.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/roadmap/RoadmapDifficultyType.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/roadmap/RoadmapNodeSaveDto.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/roadmap/RoadmapNodeSaveRequest.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/roadmap/RoadmapSaveDto.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/roadmap/RoadmapSaveRequest.java
  backend/kirikiri/src/main/java/co/kirikiri/service/mapper/RoadmapMapper.java
  backend/kirikiri/src/test/java/co/kirikiri/controller/RoadmapControllerTest.java
  backend/kirikiri/src/test/java/co/kirikiri/controller/helper/RestDocsHelper.java
  backend/kirikiri/src/test/java/co/kirikiri/controller/helper/TestObjectMapperConfig.java
  backend/kirikiri/src/test/java/co/kirikiri/domain/roadmap/RoadmapContentTest.java
  backend/kirikiri/src/test/java/co/kirikiri/domain/roadmap/RoadmapContentsTest.java
  backend/kirikiri/src/test/java/co/kirikiri/domain/roadmap/RoadmapNodeTest.java
  backend/kirikiri/src/test/java/co/kirikiri/domain/roadmap/RoadmapNodesTest.java
  backend/kirikiri/src/test/java/co/kirikiri/domain/roadmap/RoadmapTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapIntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/helper/IntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/RepositoryTest.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/roadmap/RoadmapContentRepository.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/roadmap/RoadmapNodeRepository.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/roadmap/RoadmapRepositoryTest.java
  backend/kirikiri/src/test/java/co/kirikiri/service/RoadmapServiceTest.java
  backend/kirikiri/src/test/resources/delete.sql
Labels: feature 🔅, BE 👨‍👩‍👧‍👦

#25 [feat/CK-61] 네브바 스타일링을 한다.
  client/src/App.tsx
  client/src/components/_common/header/Header.styles.ts
  client/src/components/_common/navBar/NavBar.styles.ts
  client/src/components/_common/navBar/NavBar.tsx
  client/src/components/goalRommListPage/.gitkeep
  client/src/components/goalRommListPage/GoalRoomListPage.tsx
  client/src/components/icons/svgIcons.tsx
  client/src/components/mainPage/.gitkeep
  client/src/components/mainPage/MainPage.tsx
  client/src/styles/theme.ts
Labels: feature 🔅, FE 👨‍👨‍👧

#22 [feat/CK-43] 로드맵 생성페이지 제목/소개글/본문/예상 날짜 입력기능을 구현한다
  client/.eslintrc.cjs
  client/src/App.tsx
  client/src/components/roadmapCreatePage/category/category.styles.ts
  client/src/components/roadmapCreatePage/description/description.styles.ts
  client/src/components/roadmapCreatePage/description/description.tsx
  client/src/components/roadmapCreatePage/difficulty/difficulty.styles.ts
  client/src/components/roadmapCreatePage/input/inputDescription/inputDescription.styles.ts
  client/src/components/roadmapCreatePage/input/inputDescription/inputDescription.tsx
  client/src/components/roadmapCreatePage/input/inputField/inputField.styles.ts
  client/src/components/roadmapCreatePage/input/inputField/inputField.tsx
  client/src/components/roadmapCreatePage/input/inputLabel/inputLabel.styles.ts
  client/src/components/roadmapCreatePage/input/inputLabel/inputLebel.tsx
  client/src/components/roadmapCreatePage/input/textCount/textCount.styles.ts
  client/src/components/roadmapCreatePage/input/textCount/textCount.tsx
  client/src/components/roadmapCreatePage/mainText/mainText.styles.ts
  client/src/components/roadmapCreatePage/mainText/mainText.tsx
  client/src/components/roadmapCreatePage/period/period.styles.ts
  client/src/components/roadmapCreatePage/period/period.tsx
  client/src/components/roadmapCreatePage/title/title.styles.ts
  client/src/components/roadmapCreatePage/title/title.tsx
  client/src/constants/roadmap/.gitkeep
  client/src/constants/roadmap/regex.ts
  client/src/hooks/_common/useValidateInput.ts
  client/src/myTypes/roadmap/roadmapCreate.ts
  client/src/pages/roadmapCreatePage/roadmapCreatePage.tsx
  client/src/styles/GlobalStyle.tsx
Labels: feature 🔅, FE 👨‍👨‍👧

#31 [feat/CK-93] 골룸 페이지 내부 레이아웃을 구현한다
  client/src/App.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomCertificationFeed/GoalRoomCertificationFeed.styles.ts
  client/src/components/goalRoomDahsboardPage/goalRoomCertificationFeed/GoalRoomCertificationFeed.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomDahsboardRoadmap/GoalRoomDashboardRoadmap.styles.ts
  client/src/components/goalRoomDahsboardPage/goalRoomDahsboardRoadmap/GoalRoomDashboardRoadmap.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomDahsboardTodo/GoalRoomDashboardTodo.styles.ts
  client/src/components/goalRoomDahsboardPage/goalRoomDahsboardTodo/GoalRoomDashboardTodo.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomDashboardCalender/GoalRoomDashboardCalender.styles.ts
  client/src/components/goalRoomDahsboardPage/goalRoomDashboardCalender/GoalRoomDashboardCalender.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomDashboardChat/GoalRoomDashboardChat.styles.ts
  client/src/components/goalRoomDahsboardPage/goalRoomDashboardChat/GoalRoomDashboardChat.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomDashboardContent/GoalRoomDashboardContent.styles.ts
  client/src/components/goalRoomDahsboardPage/goalRoomDashboardContent/GoalRoomDashboardContent.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomDashboardHeader/GoalRoomDashboardHeader.styles.ts
  client/src/components/goalRoomDahsboardPage/goalRoomDashboardHeader/GoalRoomDashboardHeader.tsx
  client/src/components/icons/svgIcons.tsx
  client/src/pages/goalRoomDashboardPage/GoalRoomDashboardPage.tsx
  client/src/pages/goalRoomDetailPage/.gitkeep
  client/webpack.common.js
Labels: feature 🔅, FE 👨‍👨‍👧

#33 [feat/CK-44] 로드맵 생성페이지의 로드맵 생성을 구현한다
  client/src/App.tsx
  client/src/components/_common/roadmapItem/RoadmapItem.tsx
  client/src/components/icons/SVGIcon.tsx
  client/src/components/roadmapCreatePage/category/category.tsx
  client/src/components/roadmapCreatePage/description/description.tsx
  client/src/components/roadmapCreatePage/difficulty/difficulty.tsx
  client/src/components/roadmapCreatePage/mainText/mainText.tsx
  client/src/components/roadmapCreatePage/period/period.tsx
  client/src/components/roadmapCreatePage/roadmap/roadmap.styles.ts
  client/src/components/roadmapCreatePage/roadmap/roadmap.tsx
  client/src/components/roadmapCreatePage/roadmap/roadmapItem.tsx
  client/src/components/roadmapCreatePage/roadmapCreateForm/RoadmapCreateForm.tsx
  client/src/components/roadmapCreatePage/selector/selectBox.tsx
  client/src/components/roadmapCreatePage/title/title.tsx
  client/src/components/roadmapDetailPage/roadmapDetail/RoadmapDetail.tsx
  client/src/components/roadmapListPage/categories/Categories.tsx
  client/src/components/roadmapListPage/recommandRoadmaps/RecommendRoadmaps.tsx
  client/src/components/roadmapListPage/roadmapListView/RoadmapListView.tsx
  client/src/constants/roadmap/regex.ts
  client/src/constants/roadmap/roadmap.tsx
  client/src/context/selectContext.ts
  client/src/hooks/_common/compound.ts
  client/src/myTypes/_common/.gitkeep
  client/src/myTypes/_common/compound.ts
  client/src/myTypes/_common/select.ts
  client/src/myTypes/_common/svg.ts
  client/src/myTypes/roadmap/internal.ts
  client/src/myTypes/roadmap/remote.ts
  client/src/myTypes/roadmap/roadmapCreate.ts
  client/src/pages/roadmapCreatePage/roadmapCreatePage.tsx
  client/src/utils/_common/invariantType.ts
Labels: feature 🔅, FE 👨‍👨‍👧

#34 [feat/CK-107] jest, react-testing-library, msw, storybook, useSuspendedQuery 를 세팅한다
  .gitignore
  client/.eslintrc.cjs
  client/.husky/pre-commit
  client/.storybook/main.ts
  client/.storybook/preview.ts
  client/checkUtilTests.js
  client/jest.config.js
  client/jest.setup.js
  client/package-lock.json
  client/package.json
  client/public/mockServiceWorker.js
  client/src/hooks/queries/roadmap.ts
  client/src/hooks/queries/useSuspendedQuery.ts
  client/src/index.tsx
  client/src/mocks/browser.ts
  client/src/mocks/handlers/.gitkeep
  client/src/mocks/handlers/index.ts
  client/src/mocks/handlers/userHandler.ts
  client/src/tests/utilTests/cookies.test.ts
  client/src/tests/utilTests/isQueryKey.test.ts
  client/src/tests/utilTests/logout.test.ts
  client/src/tests/utilTests/parseQueryArgs.test.ts
  client/src/utils/_common/isQueryKey.ts
  client/src/utils/_common/parseQueryArgs.ts
  client/webpack.dev.js
Labels: feature 🔅, FE 👨‍👨‍👧

#36 [feat/CK-111] webpack image-webpack-loader, OptimizeCSSAssetsPlugin 관련 build error를 해결한다.
  client/webpack.common.js
  client/webpack.prod.js
Labels: fix ⚒️, FE 👨‍👨‍👧

#35 [feat/CK-109] github actions 를 사용하여 client testing CI 를 구축한다.
  .github/workflows/ci-client-test.yml
  client/jest.config.js
  client/package.json
  client/src/App.tsx
  client/src/components/roadmapCreatePage/roadmap/roadmap.tsx
  client/src/components/roadmapCreatePage/roadmapCreateForm/RoadmapCreateForm.tsx
  client/src/hooks/_common/useValidateInput.ts
  client/src/tests/utilTests/InvariantType.test.ts
Labels: feature 🔅, FE 👨‍👨‍👧

#38 [feat/CK-112] 컴포넌트 파일명을 파스칼케이스로 변경한다
  client/src/App.tsx
  client/src/components/roadmapCreatePage/category/Category.tsx
  client/src/components/roadmapCreatePage/description/Description.tsx
  client/src/components/roadmapCreatePage/difficulty/Difficulty.tsx
  client/src/components/roadmapCreatePage/input/inputDescription/InputDescription.tsx
  client/src/components/roadmapCreatePage/input/inputField/InputField.tsx
  client/src/components/roadmapCreatePage/input/inputLabel/InputLebel.tsx
  client/src/components/roadmapCreatePage/input/textCount/TextCount.tsx
  client/src/components/roadmapCreatePage/mainText/MainText.tsx
  client/src/components/roadmapCreatePage/period/Period.tsx
  client/src/components/roadmapCreatePage/roadmap/Roadmap.tsx
  client/src/components/roadmapCreatePage/roadmap/RoadmapItem.tsx
  client/src/components/roadmapCreatePage/roadmapCreateForm/RoadmapCreateForm.tsx
  client/src/components/roadmapCreatePage/selector/SelectBox.tsx
  client/src/components/roadmapCreatePage/title/Title.tsx
  client/src/pages/roadmapCreatePage/RoadmapCreatePage.tsx
Labels: fix ⚒️, FE 👨‍👨‍👧

#26 [feat/CK-24] 골룸 목록 조회 기능을 구현한다
  backend/kirikiri/src/docs/asciidoc/goalroom.adoc
  backend/kirikiri/src/docs/asciidoc/roadmap.adoc
  backend/kirikiri/src/main/java/co/kirikiri/controller/GoalRoomController.java
  backend/kirikiri/src/main/java/co/kirikiri/controller/RoadmapController.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/BaseCreatedTimeEntity.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoom.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomPendingMember.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomPendingMembers.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomRoadmapNodes.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/vo/Period.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapContent.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapContents.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapNode.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/auth/RefreshTokenRepository.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomQueryRepository.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomQueryRepositoryImpl.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomRepository.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/dto/GoalRoomFilterType.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/roadmap/RoadmapNodeRepository.java
  backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomCreateService.java
  backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomReadService.java
  backend/kirikiri/src/main/java/co/kirikiri/service/MemberService.java
  backend/kirikiri/src/main/java/co/kirikiri/service/RoadmapCreateService.java
  backend/kirikiri/src/main/java/co/kirikiri/service/RoadmapReadService.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/ErrorResponse.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/auth/response/AuthenticationResponse.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/goalroom/GoalRoomFilterTypeDto.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/goalroom/GoalRoomRoadmapNodeDto.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/goalroom/request/GoalRoomCreateRequest.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/goalroom/request/GoalRoomRoadmapNodeRequest.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/goalroom/request/GoalRoomTodoRequest.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/goalroom/response/GoalRoomForListResponse.java
  backend/kirikiri/src/main/java/co/kirikiri/service/mapper/GoalRoomMapper.java
  backend/kirikiri/src/main/java/co/kirikiri/service/mapper/RoadmapMapper.java
  backend/kirikiri/src/test/java/co/kirikiri/common/resolver/MemberIdentifierArgumentResolverTest.java
  backend/kirikiri/src/test/java/co/kirikiri/controller/GoalRoomCreateApiTest.java
  backend/kirikiri/src/test/java/co/kirikiri/controller/GoalRoomReadApiTest.java
  backend/kirikiri/src/test/java/co/kirikiri/controller/RoadmapCreateApiTest.java
  backend/kirikiri/src/test/java/co/kirikiri/controller/RoadmapReadApiTest.java
  backend/kirikiri/src/test/java/co/kirikiri/controller/helper/ControllerTestHelper.java
  backend/kirikiri/src/test/java/co/kirikiri/domain/goalroom/GoalRoomPendingMemberTest.java
  backend/kirikiri/src/test/java/co/kirikiri/domain/goalroom/GoalRoomPendingMembersTest.java
  backend/kirikiri/src/test/java/co/kirikiri/domain/goalroom/GoalRoomRoadmapNodeTest.java
  backend/kirikiri/src/test/java/co/kirikiri/domain/goalroom/GoalRoomRoadmapNodesTest.java
  backend/kirikiri/src/test/java/co/kirikiri/domain/goalroom/GoalRoomTest.java
  backend/kirikiri/src/test/java/co/kirikiri/domain/roadmap/RoadmapContentTest.java
  backend/kirikiri/src/test/java/co/kirikiri/domain/roadmap/RoadmapNodeTest.java
  backend/kirikiri/src/test/java/co/kirikiri/domain/roadmap/RoadmapTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/AuthenticationIntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomCreateIntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomReadIntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapCreateIntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/goalroom/GoalRoomRepositoryTest.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/helper/RepositoryTest.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/roadmap/RoadmapContentRepositoryTest.java
  backend/kirikiri/src/test/java/co/kirikiri/service/GoalRoomCreateServiceTest.java
  backend/kirikiri/src/test/java/co/kirikiri/service/GoalRoomReadServiceTest.java
  backend/kirikiri/src/test/java/co/kirikiri/service/RoadmapCreateServiceTest.java
  backend/kirikiri/src/test/java/co/kirikiri/service/RoadmapReadServiceTest.java
Labels: feature 🔅, BE 👨‍👩‍👧‍👦

#24 [feat/CK-26] 골룸 참가 기능을 구현한다
  backend/kirikiri/src/docs/asciidoc/goalroom.adoc
  backend/kirikiri/src/docs/asciidoc/roadmap.adoc
  backend/kirikiri/src/main/java/co/kirikiri/controller/GoalRoomController.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/auth/RefreshToken.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoom.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomMembers.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomPendingMember.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomPendingMembers.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomRoadmapNode.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/goalroom/GoalRoomRoadmapNodes.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/member/Member.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapContent.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapContents.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapNode.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapNodes.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomPendingMemberRepository.java
  backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomCreateService.java
  backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomTodoService.java
  backend/kirikiri/src/main/java/co/kirikiri/service/MemberService.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/roadmap/response/RoadmapContentResponse.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/roadmap/response/RoadmapNodeResponse.java
  backend/kirikiri/src/main/java/co/kirikiri/service/mapper/RoadmapMapper.java
  backend/kirikiri/src/test/java/co/kirikiri/controller/AuthCreateApiTest.java
  backend/kirikiri/src/test/java/co/kirikiri/controller/GoalRoomCreateApiTest.java
  backend/kirikiri/src/test/java/co/kirikiri/controller/GoalRoomReadApiTest.java
  backend/kirikiri/src/test/java/co/kirikiri/controller/MemberCreateApiTest.java
  backend/kirikiri/src/test/java/co/kirikiri/controller/RoadmapCreateApiTest.java
  backend/kirikiri/src/test/java/co/kirikiri/controller/RoadmapReadApiTest.java
  backend/kirikiri/src/test/java/co/kirikiri/domain/goalroom/GoalRoomPendingMemberTest.java
  backend/kirikiri/src/test/java/co/kirikiri/domain/goalroom/GoalRoomPendingMembersTest.java
  backend/kirikiri/src/test/java/co/kirikiri/domain/goalroom/GoalRoomTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomCreateIntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomReadIntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapCreateIntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapReadIntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/goalroom/GoalRoomMemberRepositoryTest.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/goalroom/GoalRoomPendingMemberRepositoryTest.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/goalroom/GoalRoomRepositoryTest.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/member/MemberRepositoryTest.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/roadmap/RoadmapContentRepositoryTest.java
  backend/kirikiri/src/test/java/co/kirikiri/persistence/roadmap/RoadmapRepositoryTest.java
  backend/kirikiri/src/test/java/co/kirikiri/service/GoalRoomCreateServiceTest.java
  backend/kirikiri/src/test/java/co/kirikiri/service/GoalRoomReadServiceTest.java
  backend/kirikiri/src/test/java/co/kirikiri/service/MemberServiceTest.java
  backend/kirikiri/src/test/java/co/kirikiri/service/RoadmapCreateServiceTest.java
  backend/kirikiri/src/test/java/co/kirikiri/service/RoadmapReadServiceTest.java
  backend/kirikiri/src/test/resources/org/springframework/restdocs/templates/path-parameters.snippet
Labels: feature 🔅, BE 👨‍👩‍👧‍👦
