Repository woowacourse-teams/2023-co-kirikiri, pull requests merged in 2023-09, with the labels that each got.

#141 [feat/CK-179] 로드맵 카테고리 생성을 구현한다
  backend/kirikiri/src/docs/asciidoc/roadmap.adoc
  backend/kirikiri/src/main/java/co/kirikiri/controller/RoadmapController.java
  backend/kirikiri/src/main/java/co/kirikiri/domain/roadmap/RoadmapCategory.java
  backend/kirikiri/src/main/java/co/kirikiri/persistence/roadmap/RoadmapCategoryRepository.java
  backend/kirikiri/src/main/java/co/kirikiri/service/RoadmapCreateService.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/roadmap/request/RoadmapCategorySaveRequest.java
  backend/kirikiri/src/main/java/co/kirikiri/service/mapper/RoadmapMapper.java
  backend/kirikiri/src/test/java/co/kirikiri/controller/RoadmapCreateApiTest.java
  backend/kirikiri/src/test/java/co/kirikiri/domain/roadmap/RoadmapCategoryTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapCreateIntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapReadIntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapReadOrderIntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/fixture/RoadmapAPIFixture.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/helper/InitIntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/helper/TestConfig.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/helper/TestTransactionService.java
  backend/kirikiri/src/test/java/co/kirikiri/service/RoadmapCreateServiceTest.java
Labels: BE 👨‍👩‍👧‍👦

#145 [feat/CK-190] 골룸 생성 시 투두리스트를 필수로 입력받는 로직을 제거한다
  backend/kirikiri/src/main/java/co/kirikiri/persistence/goalroom/GoalRoomQueryRepositoryImpl.java
  backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomCreateService.java
  backend/kirikiri/src/main/java/co/kirikiri/service/GoalRoomReadService.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/goalroom/GoalRoomCreateDto.java
  backend/kirikiri/src/main/java/co/kirikiri/service/dto/goalroom/request/GoalRoomCreateRequest.java
  backend/kirikiri/src/main/java/co/kirikiri/service/mapper/GoalRoomMapper.java
  backend/kirikiri/src/test/java/co/kirikiri/controller/GoalRoomCreateApiTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomCreateIntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomReadIntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/GoalRoomSchedulerIntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapReadOrderIntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapReviewCreateIntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/RoadmapSchedulerIntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/fixture/GoalRoomAPIFixture.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/helper/IntegrationTest.java
  backend/kirikiri/src/test/java/co/kirikiri/integration/helper/TestTransactionService.java
  backend/kirikiri/src/test/java/co/kirikiri/service/GoalRoomCreateServiceTest.java
Labels: feature 🔅, BE 👨‍👩‍👧‍👦

#149 [feat/CK-186] 골룸생성부분의 todo로직 제거
  client/src/components/goalRoomCreatePage/createGoalRoomForm/CreateGoalRoomForm.tsx
  client/src/components/goalRoomCreatePage/createGoalRoomForm/createGoalRoomValidations.ts
  client/src/components/goalRoomCreatePage/todoListSection/TodoListSection.styles.ts
  client/src/components/goalRoomCreatePage/todoListSection/TodoListSection.tsx
  client/src/myTypes/goalRoom/remote.ts
Labels: fix ⚒️, FE 👨‍👨‍👧

#150 [feat/CK-191] Naver Oauth를 구현한다
  client/src/apis/user.ts
  client/src/components/icons/svgIcons.tsx
  client/src/components/loginPage/loginOptions/LoginOptions.styles.ts
  client/src/components/loginPage/loginOptions/LoginOptions.tsx
  client/src/constants/@queryKeys/queryKeys.ts
  client/src/hooks/queries/user.ts
  client/src/myTypes/user/remote.ts
Labels: feature 🔅, FE 👨‍👨‍👧

#151 [feat/CK-191] Naver Oauth를 구현한다
  client/src/apis/user.ts
  client/src/components/icons/svgIcons.tsx
  client/src/components/loginPage/loginOptions/LoginOptions.styles.ts
  client/src/components/loginPage/loginOptions/LoginOptions.tsx
  client/src/constants/@queryKeys/queryKeys.ts
  client/src/hooks/queries/user.ts
  client/src/myTypes/user/remote.ts
Labels: feature 🔅, FE 👨‍👨‍👧

#140 [feat/CK-185] 툴팁(Tool Tip)을 구현한다
  client/src/components/_common/toolTip/ToolTip.styles.ts
  client/src/components/_common/toolTip/ToolTip.tsx
Labels: feature 🔅, FE 👨‍👨‍👧

#146 [feat/CK-184] 회원가입 API 수정을 반영하고 유효성 검사를 구현한다
  client/src/components/_providers/UserInfoProvider.tsx
  client/src/components/icons/svgIcons.tsx
  client/src/components/loginPage/loginContent/LoginContent.styles.ts
  client/src/components/loginPage/loginForm/LoginForm.styles.ts
  client/src/components/loginPage/loginForm/LoginForm.tsx
  client/src/components/loginPage/loginOptions/LoginOptions.styles.ts
  client/src/components/myPage/myPageGoalRoomTab/MyPageGoalRoomTab.styles.ts
  client/src/components/roadmapListPage/roadmapListView/RoadmapListView.styles.ts
  client/src/components/signUpPage/signUpForm/SignUpForm.styles.ts
  client/src/components/signUpPage/signUpForm/SignUpForm.tsx
  client/src/components/signUpPage/signUpForm/signUpValidations.ts
  client/src/constants/user/regex.ts
  client/src/constants/user/signUpValidation.ts
  client/src/hooks/_common/useIdentifyUser.ts
  client/src/hooks/user/useSignUpFormValidation.ts
  client/src/myTypes/user/remote.ts
  client/src/pages/signUpPage/SignUpPage.tsx
  client/src/tests/utilTests/isValidUserInfo.test.ts
Labels: FE 👨‍👨‍👧

#152 [feat/CK-191] 네이버 OAuth를 구현한다
  client/src/App.tsx
  client/src/apis/user.ts
  client/src/components/loginPage/OAuthRedirect.tsx
  client/src/components/loginPage/loginOptions/LoginOptions.tsx
  client/src/hooks/queries/user.ts
  client/src/myTypes/user/remote.ts
Labels: feature 🔅, FE 👨‍👨‍👧

#153 [feat/CK-193] 인증 횟수에 툴팁을 적용하고 오타를 수정한다
  client/src/components/_common/InputField/InputField.styles.ts
  client/src/components/_common/InputField/InputField.tsx
  client/src/components/_common/toolTip/ToolTip.styles.ts
  client/src/components/_common/toolTip/ToolTip.tsx
  client/src/components/goalRoomCreatePage/createGoalRoomForm/CreateGoalRoomForm.tsx
  client/src/components/goalRoomCreatePage/nodeSection/NodeSection.tsx
  client/src/components/roadmapDetailPage/roadmapNodeList/roadmapNodeList.styles.ts
Labels: FE 👨‍👨‍👧

#155 [feat/CK-192] 툴팁 적용 및 골룸 개선
  client/src/apis/axios/client.ts
  client/src/components/_common/toolTip/ToolTip.styles.ts
  client/src/components/goalRoomDahsboardPage/goalRoomCertificationFeed/GoalRoomCertificationFeed.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomCertificationFeed/certificationFeedModal/CertificationModal.styles.ts
  client/src/components/goalRoomDahsboardPage/goalRoomDahsboardTodo/GoalRoomDashboardTodo.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomUserRanking/GoalRoomUserRanking.tsx
  client/src/hooks/queries/goalRoom.ts
  client/src/styles/theme.ts
Labels: feature 🔅, FE 👨‍👨‍👧

#156 [feat/CK-196] 릴리즈 전 수정사항 반영
  client/src/components/_common/roadmapItem/RoadmapItem.tsx
  client/src/components/goalRoomCreatePage/createGoalRoom/CreateGoalRoom.tsx
  client/src/components/goalRoomCreatePage/createGoalRoomForm/CreateGoalRoomForm.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomDashboardBarricade/GoalRoomDashboardBarricade.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomDashboardHeader/GoalRoomDashboardHeader.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomUserRanking/GoalRoomUserRanking.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomUserRanking/goalRoomRankingModal/GoalRoomRankingModal.tsx
  client/src/components/goalRoomListPage/goalRoomDetail/GoalRoomDetailDialogContent.tsx
  client/src/components/goalRoomListPage/goalRoomList/GoalRoomList.tsx
  client/src/components/myPage/myPageGoalRoomTab/MyPageGoalRoomTab.tsx
  client/src/components/roadmapDetailPage/roadmapDetail/RoadmapDetail.tsx
  client/src/components/roadmapListPage/roadmapList/RoadmapList.tsx
  client/src/components/roadmapListPage/roadmapListView/RoadmapListView.tsx
  client/src/constants/goalRoom/goalRoomValidation.ts
  client/src/hooks/queries/goalRoom.ts
  client/src/pages/goalRoomCreatePage/GoalRoomCreatePage.tsx
  client/src/pages/mainPage/MainPage.styles.ts
  client/src/pages/mainPage/MainPage.tsx
Labels: fix ⚒️, FE 👨‍👨‍👧

#157 [feat/CK-195] 노드 목록의 가시성 향상한다
  client/src/components/roadmapDetailPage/roadmapNodeList/roadmapNodeList.styles.ts
Labels: FE 👨‍👨‍👧

#158 Feature/ck 196
  client/src/components/roadmapListPage/roadmapList/RoadmapList.tsx
Labels: fix ⚒️, FE 👨‍👨‍👧

#160 [feat/CK-197] 릴리즈 전 최종 QA 반영
  client/src/components/_common/roadmapItem/RoadmapItem.styles.ts
  client/src/components/_common/roadmapItem/RoadmapItem.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomCertificationFeed/certificationFeedModal/CertificationFeedModal.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomCertificationFeed/certificationFeedModal/CertificationModal.styles.ts
  client/src/components/myPage/myPageContent/MyPageContent.tsx
  client/src/components/myPage/myPageGoalRoomTab/MyPageGoalRoomTab.tsx
  client/src/components/roadmapDetailPage/roadmapNodeList/RoadmapNodeList.tsx
  client/src/components/roadmapDetailPage/roadmapNodeList/roadmapNodeList.styles.ts
  client/src/index.tsx
Labels: fix ⚒️, feature 🔅, FE 👨‍👨‍👧

#162 [feat/CK-198] token reissue 에러 핸들링 및 session Handler wrapper component 구현
  client/src/App.tsx
  client/src/apis/axios/client.ts
  client/src/components/_common/sessionHandler/SessionHandler.tsx
Labels: fix ⚒️, FE 👨‍👨‍👧

#163 [feat/CK-199] 프론트엔드의 최적화를 진행한다
  client/public/index.html
  client/src/App.tsx
  client/src/assets/assets.d.ts
  client/src/assets/images/cryingelephant.avif
  client/src/assets/images/elephant.avif
  client/src/assets/images/logo.avif
  client/src/assets/images/podium.avif
  client/src/components/_common/errorBoundary/ErrorBoundaryFallback.tsx
  client/src/components/_common/navBar/NavBar.tsx
  client/src/components/_common/roadmapItem/RoadmapItem.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomUserRanking/GoalRoomUserRanking.styles.ts
  client/src/components/goalRoomDahsboardPage/goalRoomUserRanking/GoalRoomUserRanking.tsx
  client/src/components/goalRoomListPage/goalRoomList/GoalRoomFilter.tsx
  client/src/components/goalRoomListPage/goalRoomList/GoalRoomItem.tsx
  client/src/components/goalRoomListPage/goalRoomList/GoalRoomList.tsx
  client/src/components/goalRoomListPage/goalRoomList/goalRoomList.styles.ts
  client/src/components/loginPage/loginContent/LoginContent.tsx
  client/src/components/roadmapDetailPage/roadmapDetail/RoadmapDetail.styles.ts
  client/src/components/roadmapDetailPage/roadmapNodeList/RoadmapNodeList.tsx
  client/src/components/roadmapDetailPage/roadmapNodeList/roadmapNodeList.styles.ts
  client/src/components/roadmapListPage/categories/Categories.tsx
  client/src/components/roadmapListPage/roadmapSearch/RoadmapSearch.tsx
  client/src/components/signUpPage/signUpForm/SignUpForm.tsx
  client/src/myTypes/_common/global.d.ts
  client/src/pages/mainPage/MainPage.tsx
  client/src/styles/GlobalStyle.tsx
  client/webpack.common.js
  client/webpack.prod.js
Labels: enhancement, FE 👨‍👨‍👧

#166 [hotfix/CK-208] 마이 페이지에 이메일을 도출한다
  client/src/components/_providers/UserInfoProvider.tsx
  client/src/components/myPage/myPageUserInfo/MyPageUserInfo.tsx
  client/src/hooks/_common/useIdentifyUser.ts
  client/src/myTypes/user/remote.ts
  client/src/tests/utilTests/isValidUserInfo.test.ts
Labels: feature 🔅

#168 [feat/CK-201] Slider Compound 컴포넌트를 구현한다
  client/src/components/_common/slider/Slider.styles.ts
  client/src/components/_common/slider/Slider.tsx
  client/src/components/icons/svgIcons.tsx
  client/src/components/signUpPage/signUpForm/SignUpForm.styles.ts
  client/src/hooks/_common/useSlider.ts
  client/src/styles/GlobalStyle.tsx
  client/src/styles/media.ts
Labels: feature 🔅, FE 👨‍👨‍👧

#172 [feat/CK-213] 로드맵 검색 오류를 해결한다.
  client/src/components/roadmapListPage/roadmapList/RoadmapList.tsx
  client/src/components/roadmapListPage/roadmapSearch/NoResult.tsx
  client/src/components/roadmapListPage/roadmapSearch/RoadmapSearch.tsx
  client/src/components/roadmapListPage/roadmapSearch/RoadmapSearchResult.tsx
  client/src/components/roadmapListPage/roadmapSearch/roadmapSearch.styles.ts
Labels: fix ⚒️, FE 👨‍👨‍👧

#171 [feat/CK-212] 로드맵 생성페이지 오류를 해결한다.
  client/src/components/roadmapCreatePage/difficulty/Difficulty.tsx
  client/src/components/roadmapCreatePage/roadmapCreateForm/RoadmapCreateForm.tsx
  client/src/components/roadmapCreatePage/tag/Tag.tsx
  client/src/constants/roadmap/tag.ts
  client/src/hooks/roadmap/useCollectRoadmapData.ts
  client/src/hooks/roadmap/useCreateTag.ts
  client/src/myTypes/roadmap/internal.ts
Labels: fix ⚒️, FE 👨‍👨‍👧
