Repository woowacourse-teams/2023-co-kirikiri, pull requests merged in 2023-10, with the labels that each got.

#169 [feat/CK-209] 새로고침 시 로그인 페이지로 이동하는 버그를 해결한다.
  client/src/App.tsx
  client/src/components/_common/privateRouter/PrivateRouter.tsx
Labels: fix ⚒️, FE 👨‍👨‍👧

#173 [feat/CK-210] 로드맵 디테일 페이지의 UI를 개편한다.
  client/src/components/icons/svgIcons.tsx
  client/src/components/roadmapDetailPage/extraInfo/ExtraInfo.styles.ts
  client/src/components/roadmapDetailPage/extraInfo/ExtraInfo.tsx
  client/src/components/roadmapDetailPage/introduction/Introduction.styles.ts
  client/src/components/roadmapDetailPage/introduction/Introduction.tsx
  client/src/components/roadmapDetailPage/nodeContent/NodeContent.styles.ts
  client/src/components/roadmapDetailPage/nodeContent/NodeContent.tsx
  client/src/components/roadmapDetailPage/roadmapDetail/RoadmapDetail.styles.ts
  client/src/components/roadmapDetailPage/roadmapDetail/RoadmapDetail.tsx
Labels: feature 🔅, FE 👨‍👨‍👧

#170 [feat/CK-211] Google Analytics 를 적용한다.
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/_common/routeChangeTracker/RouteChangeTracker.tsx
  client/webpack.common.js
Labels: feature 🔅, FE 👨‍👨‍👧

#174 [hotfix/CK-214] 개행 문자에 대한 개행이 이루어지지 않던 문제 해결
  client/src/styles/GlobalStyle.tsx
Labels: fix ⚒️, FE 👨‍👨‍👧

#175 [hotfix/CK-214] slider의 너비가 줄어들지 않는 오류를 해결한다.
  client/src/components/_common/slider/Slider.styles.ts
Labels: fix ⚒️, FE 👨‍👨‍👧

#177 [feat/CK-216] 인증/인가 관련 페이지에 UI 모바일 대응을 한다.
  client/src/components/_common/SingleCard/SingleCard.styles.ts
  client/src/components/_common/backButton/BackButton.styles.ts
  client/src/components/_common/backButton/BackButton.tsx
  client/src/components/loginPage/loginContent/LoginContent.styles.ts
  client/src/components/loginPage/loginContent/LoginContent.tsx
  client/src/components/loginPage/loginForm/LoginForm.styles.ts
  client/src/components/loginPage/loginForm/LoginForm.tsx
  client/src/components/loginPage/loginOptions/LoginOptions.styles.ts
  client/src/components/loginPage/loginOptions/LoginOptions.tsx
  client/src/components/signUpPage/signUpForm/SignUpForm.styles.ts
  client/src/components/signUpPage/signUpForm/SignUpForm.tsx
  client/src/styles/theme.ts
Labels: feature 🔅, FE 👨‍👨‍👧

#178 [feat/CK-218] 로드맵 리스트 페이지 모바일 대응을 한다.
  client/src/components/_common/roadmapItem/RoadmapItem.styles.ts
  client/src/components/_common/roadmapItem/RoadmapItem.tsx
  client/src/components/roadmapListPage/categories/Categories.styles.ts
  client/src/components/roadmapListPage/roadmapList/RoadmapList.styles.ts
  client/src/components/roadmapListPage/roadmapListView/RoadmapListView.styles.ts
  client/src/components/roadmapListPage/roadmapListView/RoadmapListView.tsx
  client/src/components/roadmapListPage/roadmapSearch/RoadmapSearch.tsx
  client/src/components/roadmapListPage/roadmapSearch/roadmapSearch.styles.ts
  client/src/styles/GlobalStyle.tsx
Labels: feature 🔅, FE 👨‍👨‍👧

#179 [feat/CK-219] 로드맵 생성 페이지 모바일 대응을 한다.
  client/src/components/roadmapCreatePage/category/category.styles.ts
Labels: feature 🔅, FE 👨‍👨‍👧

#180 [feat/CK-220] 로드맵 디테일 페이지 모바일 대응을 한다.
  client/src/components/_common/slider/Slider.styles.ts
  client/src/components/roadmapDetailPage/extraInfo/ExtraInfo.styles.ts
  client/src/components/roadmapDetailPage/extraInfo/ExtraInfo.tsx
  client/src/components/roadmapDetailPage/introduction/Introduction.styles.ts
  client/src/components/roadmapDetailPage/introduction/Introduction.tsx
  client/src/components/roadmapDetailPage/nodeContent/NodeContent.styles.ts
  client/src/components/roadmapDetailPage/nodeContent/NodeContent.tsx
  client/src/components/roadmapDetailPage/roadmapDetail/RoadmapDetail.styles.ts
  client/src/components/roadmapDetailPage/roadmapDetail/RoadmapDetail.tsx
Labels: feature 🔅, FE 👨‍👨‍👧

#182 [feat/CK-217] 골룸 목록 조회 페지이의 모바일 대응 및 로드맵 모달을 구현한다.
  client/src/components/goalRoomDahsboardPage/goalRoomCertificationFeed/GoalRoomCertificationFeed.styles.ts
  client/src/components/goalRoomDahsboardPage/goalRoomDahsboardRoadmap/GoalRoomDashboardRoadmap.styles.ts
  client/src/components/goalRoomDahsboardPage/goalRoomDahsboardRoadmap/GoalRoomDashboardRoadmap.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomDahsboardRoadmap/roadmapModal/RoadmapModal.styles.ts
  client/src/components/goalRoomDahsboardPage/goalRoomDahsboardRoadmap/roadmapModal/RoadmapModal.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomDashboardContent/GoalRoomDashboardContent.styles.ts
  client/src/components/goalRoomDahsboardPage/goalRoomDashboardContent/GoalRoomDashboardContent.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomDashboardHeader/GoalRoomDashboardHeader.styles.ts
  client/src/components/goalRoomDahsboardPage/goalRoomUserRanking/GoalRoomUserRanking.styles.ts
  client/src/components/goalRoomDahsboardPage/goalRoomUserRanking/GoalRoomUserRanking.tsx
Labels: feature 🔅, FE 👨‍👨‍👧

#181 [feat/CK-221] 골룸 목록 조회 페지이의 모바일 대응을 한다.
  client/src/components/goalRoomListPage/goalRoomList/GoalRoomItem.tsx
  client/src/components/goalRoomListPage/goalRoomList/GoalRoomList.tsx
  client/src/components/goalRoomListPage/goalRoomList/goalRoomList.styles.ts
  client/src/styles/GlobalStyle.tsx
Labels: FE 👨‍👨‍👧

#184 [feat/CK-224] 네브바의 모바일 대응을 수행한다
  client/src/components/_common/navBar/NavBar.styles.ts
Labels: FE 👨‍👨‍👧

#187 [feat/CK-228] 골룸 관련 API를 동기화한다.
  client/src/components/goalRoomCreatePage/createGoalRoom/CreateGoalRoom.tsx
  client/src/components/goalRoomCreatePage/createGoalRoomForm/CreateGoalRoomForm.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomDahsboardRoadmap/GoalRoomDashboardRoadmap.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomDahsboardRoadmap/roadmapModal/RoadmapModal.tsx
  client/src/components/goalRoomDahsboardPage/goalRoomDashboardContent/GoalRoomDashboardContent.tsx
  client/src/myTypes/goalRoom/internal.ts
  client/src/myTypes/roadmap/internal.ts
Labels: FE 👨‍👨‍👧
